# Generated by Django 5.2.11 on 2026-03-14 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pois', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Vĩ độ')),
                ('long', models.FloatField(verbose_name='Kinh độ')),
                ('timestamp', models.DateTimeField(verbose_name='Thời điểm ghi')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Vết di chuyển',
                'verbose_name_plural': 'Vết di chuyển',
                'db_table': 'breadcrumb_logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='breadcrumb_user_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='NarrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Thời điểm bắt đầu')),
                ('duration', models.IntegerField(blank=True, help_text='Null cho đến khi client gửi end event.', null=True, verbose_name='Thời lượng đã nghe (giây)')),
                ('trigger_type', models.CharField(choices=[('AUTO', 'Tự động (Geofence)'), ('QR', 'Quét mã QR')], default='AUTO', max_length=10, verbose_name='Loại kích hoạt')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narration_logs', to='pois.poi', verbose_name='Điểm tham quan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narration_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử nghe',
                'verbose_name_plural': 'Lịch sử nghe',
                'db_table': 'narration_logs',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'poi', 'trigger_type', 'start_time'], name='narration_antispam_idx')],
            },
        ),
    ]
