# Generated by Django 5.2.11 on 2026-03-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên điểm')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('geofence_radius', models.IntegerField(default=50, help_text='Bán kính tính bằng mét để kích hoạt Narration Engine.', verbose_name='Bán kính Geofence (mét)')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Danh mục')),
                ('qr_code_data', models.CharField(blank=True, default='', help_text='Dữ liệu được mã hoá trong QR Code tại điểm tham quan.', max_length=512, verbose_name='Dữ liệu QR Code')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Điểm tham quan',
                'verbose_name_plural': 'Điểm tham quan',
                'db_table': 'pois',
                'ordering': ['name'],
            },
        ),
    ]
