# Generated by Django 5.2.11 on 2026-03-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Tên cơ sở')),
                ('menu_details', models.JSONField(blank=True, default=dict, help_text='JSON: {"must_try": ["món A", "món B"], "price_range": "50k-100k"}', verbose_name='Chi tiết menu')),
                ('opening_hours', models.CharField(blank=True, default='', help_text='Ví dụ: 07:00 - 22:00', max_length=100, verbose_name='Giờ mở cửa')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='pois.poi', verbose_name='Điểm tham quan')),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
                'db_table': 'partners',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True, default='', help_text='Để trống nếu loại là TTS (nội dung lấy từ POI.description).', verbose_name='URL file âm thanh')),
                ('language', models.CharField(help_text='Mã ngôn ngữ: vi, en, ja, ko, zh, ...', max_length=10, verbose_name='Ngôn ngữ')),
                ('voice_region', models.CharField(blank=True, default='', help_text='mien_nam, mien_bac, mien_trung, usa, uk, ...', max_length=50, verbose_name='Vùng giọng đọc')),
                ('media_type', models.CharField(choices=[('AUDIO', 'File âm thanh thu sẵn'), ('TTS', 'Text-to-Speech')], default='AUDIO', max_length=10, verbose_name='Loại media')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pois.poi', verbose_name='Điểm tham quan')),
            ],
            options={
                'verbose_name': 'File âm thanh',
                'verbose_name_plural': 'File âm thanh',
                'db_table': 'poi_media',
                'ordering': ['language', 'voice_region'],
                'indexes': [models.Index(fields=['poi', 'language', 'voice_region'], name='media_poi_lang_region_idx')],
            },
        ),
    ]
