# Generated by Django 5.2.11 on 2026-03-18 02:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_partner_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('impression', 'Hiển thị card'), ('click', 'Click vào card'), ('call', 'Gọi điện'), ('website', 'Truy cập website'), ('direction', 'Lấy chỉ đường')], max_length=20, verbose_name='Loại tương tác')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Tương tác Partner',
                'verbose_name_plural': 'Tương tác Partner',
                'db_table': 'partner_interactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PartnerIntroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(help_text='ID của file media từ bảng core.media (upload vào Cloudinary)', verbose_name='Mã file media')),
                ('language', models.CharField(default='vi', help_text='Mã ngôn ngữ: vi, en, ja, ko, ...', max_length=10, verbose_name='Ngôn ngữ')),
                ('voice_region', models.CharField(blank=True, default='', help_text='mien_bac, mien_trung, mien_nam, usa, uk, ...', max_length=50, verbose_name='Vùng giọng đọc')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'File giới thiệu Partner',
                'verbose_name_plural': 'File giới thiệu Partner',
                'db_table': 'partner_intro_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đối tác', 'verbose_name_plural': 'Đối tác'},
        ),
        migrations.AddField(
            model_name='partner',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Bị từ chối')], default='PENDING', help_text='PENDING: chờ duyệt, APPROVED: hiển thị, REJECTED: không hiển thị', max_length=10, verbose_name='Trạng thái duyệt'),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='partner',
            name='intro_audio',
            field=models.URLField(blank=True, default='', help_text='File audio giới thiệu (ưu tiên phát nếu có)', verbose_name='URL file audio tự thu'),
        ),
        migrations.AddField(
            model_name='partner',
            name='intro_text',
            field=models.TextField(blank=True, default='', help_text='Mô tả giới thiệu về cơ sở (sẽ chuyển thành TTS nếu không có file audio)', verbose_name='Nội dung giới thiệu'),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Tài khoản Partner quản lý hồ sơ này', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['user', 'approval_status'], name='partner_user_approval_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['poi', 'approval_status'], name='partner_poi_approval_idx'),
        ),
        migrations.AddField(
            model_name='partnerinteraction',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='pois.partner', verbose_name='Đối tác'),
        ),
        migrations.AddField(
            model_name='partnerinteraction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null nếu user không đăng nhập (anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='partnerintromedia',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_media', to='pois.partner', verbose_name='Đối tác'),
        ),
        migrations.AddIndex(
            model_name='partnerinteraction',
            index=models.Index(fields=['partner', 'interaction_type', 'timestamp'], name='partner_interaction_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerintromedia',
            index=models.Index(fields=['partner', 'language', 'voice_region'], name='partner_intro_lang_idx'),
        ),
    ]
