# Generated by Django 5.2.11 on 2026-03-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0003_partnerinteraction_partnerintromedia_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_user_approval_idx',
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_poi_approval_idx',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='intro_audio',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={
                'ordering': ['business_name'],
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
            },
        ),
    ]
