# Generated by Django 5.2.11 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0004_align_partner_with_erd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.IntegerField(
                choices=[
                    (0, 'Không hoạt động'),
                    (1, 'Hoạt động'),
                    (2, 'Chờ phê duyệt'),
                ],
                default=2,
                verbose_name='Trạng thái',
            ),
        ),
    ]
