# Generated by Django 5.2.11 on 2026-03-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0005_partner_status_pending_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='intro_text',
            field=models.TextField(blank=True, default='', help_text='Đoạn văn ngắn giới thiệu cơ sở cho TTS. Để trống để tự động sinh từ thông tin menu.', verbose_name='Đoạn giới thiệu TTS'),
        ),
    ]
