# Generated by Django 5.2.11 on 2026-03-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0006_add_partner_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='qr_url',
            field=models.URLField(blank=True, default='', help_text='URL sẽ mã hoá thành QR Code hiện trên app (ví dụ: link Google Maps, Facebook, Shopeefood...)', max_length=500, verbose_name='Link QR (menu / mạng xã hội)'),
        ),
    ]
