# Generated by Django 5.2.11 on 2026-03-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0007_add_partner_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tts_content',
            field=models.TextField(blank=True, default='', help_text='Văn bản sẽ được đọc TTS. Nếu để trống, hệ thống dùng mô tả gốc của POI. Nhấn "Tự động dịch" để tự động điền từ mô tả tiếng Việt.', verbose_name='Nội dung TTS (bản dịch)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_url',
            field=models.URLField(blank=True, default='', help_text='Để trống nếu loại là TTS.', verbose_name='URL file âm thanh'),
        ),
    ]
