# Generated by Django 5.2.11 on 2026-03-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0011_partner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='translated_name',
            field=models.CharField(blank=True, default='', help_text='Tên POI bằng ngôn ngữ này (ví dụ: tên tiếng Nhật).', max_length=255, verbose_name='Tên đã dịch'),
        ),
    ]
