# Generated by Django 5.2.11 on 2026-03-28 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0012_media_translated_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='poi',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('latitude', 'longitude'), name='uniq_poi_active_lat_lng'),
        ),
    ]
