# Generated by Django 5.2.11 on 2026-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0014_poi_partner_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='URL ảnh bìa đại diện của điểm tham quan (upload lên Cloudinary).', max_length=1024, verbose_name='Ảnh bìa'),
        ),
    ]
