# Generated by Django 5.2.11 on 2026-05-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0015_add_poi_cover_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_api_key_encrypted', models.BinaryField(blank=True, default=b'', help_text='Tự động mã hóa khi lưu. Không chỉnh sửa trực tiếp trường này.', verbose_name='API Key (Encrypted)')),
                ('tts_model', models.CharField(default='gemini-2.5-flash-preview-tts', help_text='Tên model Gemini TTS, ví dụ: gemini-2.5-flash-preview-tts', max_length=100, verbose_name='Model TTS')),
                ('default_voice', models.CharField(default='Aoede', help_text='Giọng nói mặc định khi không chỉ định cụ thể.', max_length=50, verbose_name='Giọng mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Gemini AI',
                'verbose_name_plural': 'Cấu hình Gemini AI',
                'db_table': 'gemini_api_config',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='ai_voice',
            field=models.CharField(blank=True, default='', help_text='Tên giọng Gemini TTS (Aoede, Kore, Puck, ...). Để trống để dùng giọng mặc định Aoede.', max_length=50, verbose_name='Giọng Gemini AI'),
        ),
    ]
