# Generated by Django 5.2.11 on 2026-05-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0016_gemini_ai_tts'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='ai_tts_quota',
            field=models.PositiveIntegerField(default=0, help_text='Số lượt tạo âm thanh TTS bằng Gemini AI.', verbose_name='Số lượt TTS AI còn lại'),
        ),
    ]
