# Generated by Django 5.2.11 on 2026-05-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0017_partner_ai_tts_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='ai_translate_quota',
            field=models.PositiveIntegerField(default=0, help_text='Số lượt dịch tự động tất cả ngôn ngữ POI bằng Gemini AI.', verbose_name='Số lượt Dịch AI còn lại'),
        ),
    ]
