# Generated by Django 5.2.11 on 2026-03-14 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=255, verbose_name='Tên tour')),
                ('is_suggested', models.BooleanField(default=False, verbose_name='Tour đề xuất')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'tours',
                'ordering': ['-id'],
            },
        ),
    ]
