# Generated by Django 5.2.11 on 2026-03-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_partner_media'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_POI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_pois', to='pois.poi', verbose_name='Điểm tham quan')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_pois', to='tours.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Điểm tham quan của Tour',
                'verbose_name_plural': 'Các điểm tham quan của Tour',
                'db_table': 'tour_pois',
                'ordering': ['tour', 'sequence_order'],
            },
        ),
    ]
