# Generated by Django 5.2.11 on 2026-03-14 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_poi',
            name='sequence_order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự'),
        ),
    ]
