# Generated by Django 5.2.11 on 2026-03-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='translated_description',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"en": "Desc", "ja": "Desc"}', verbose_name='Mô tả tour (đa ngôn ngữ)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='translated_name',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"en": "Name", "ja": "Name"}', verbose_name='Tên tour (đa ngôn ngữ)'),
        ),
    ]
