# Generated by Django 5.2.11 on 2026-03-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_translated_description_tour_translated_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Đánh dấu tour cần trả phí mở khóa', verbose_name='Tour Premium'),
        ),
        migrations.AddField(
            model_name='tour',
            name='premium_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, help_text='Giá mở khóa tour premium (đơn vị VND). Bỏ trống hoặc 0 nếu miễn phí.', verbose_name='Giá Premium (VND)'),
        ),
    ]
