# Generated by Django 5.2.11 on 2026-03-28 02:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_sample_invoice'),
        ('tours', '0009_tour_is_premium_tour_premium_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày mua')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_purchase', to='payments.invoice')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tours.tour', verbose_name='Tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mua Tour Premium',
                'verbose_name_plural': 'Mua Tour Premium',
                'db_table': 'tour_purchases',
                'ordering': ['-purchased_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tour'), name='uniq_user_tour_purchase')],
            },
        ),
    ]
