# Generated by Django 5.2.11 on 2026-05-07 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='ai_tts_price_vnd',
            field=models.PositiveBigIntegerField(default=25000, help_text='Phí Partner phải trả để được sử dụng tính năng Gemini AI TTS.', verbose_name='Phí sử dụng AI TTS (VND)'),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='partner_premium_price_vnd',
            field=models.PositiveBigIntegerField(default=100000, help_text='Giá mở khóa gói premium cho tài khoản partner.', verbose_name='Giá gói Partner Premium (VND)'),
        ),
        migrations.CreateModel(
            name='AiTtsPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày mua')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tts_purchase', to='payments.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tts_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mua AI TTS',
                'verbose_name_plural': 'Mua AI TTS',
                'db_table': 'ai_tts_purchases',
                'ordering': ['-purchased_at'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_user_ai_tts_purchase')],
            },
        ),
    ]
