# Generated by Django 5.2.11 on 2026-05-07 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_ai_tts_purchase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aittspurchase',
            name='uniq_user_ai_tts_purchase',
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='ai_tts_quota_per_purchase',
            field=models.PositiveIntegerField(default=5, help_text='Số lần tạo TTS mà Partner nhận được sau mỗi lần thanh toán.', verbose_name='Số lượt TTS mỗi lần mua'),
        ),
        migrations.AlterField(
            model_name='aittspurchase',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tts_purchases', to='payments.invoice'),
        ),
    ]
