# Generated by Django 5.2.11 on 2026-05-07 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_aittspurchase_uniq_user_ai_tts_purchase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='ai_translate_price_vnd',
            field=models.PositiveBigIntegerField(default=50000, help_text='Phí Partner phải trả để được sử dụng tính năng Gemini AI Dịch.', verbose_name='Phí dịch AI (VND)'),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='ai_translate_quota_per_purchase',
            field=models.PositiveIntegerField(default=10, help_text='Số lần dịch mà Partner nhận được sau mỗi lần thanh toán.', verbose_name='Số lượt Dịch mỗi lần mua'),
        ),
        migrations.CreateModel(
            name='AiTranslatePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày mua')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_translate_purchases', to='payments.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_translate_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mua AI Dịch',
                'verbose_name_plural': 'Mua AI Dịch',
                'db_table': 'ai_translate_purchases',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
