# Generated by Django 5.2.11 on 2026-03-06 15:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.IntegerField(blank=True, help_text='ID của POI (sẽ chuyển thành ForeignKey khi POI model sẵn sàng)', null=True, verbose_name='Mã điểm tham quan')),
                ('file', cloudinary.models.CloudinaryField(help_text='Upload file ảnh, audio hoặc video lên Cloudinary', max_length=255, verbose_name='File')),
                ('language', models.CharField(default='vi', help_text='Mã ngôn ngữ: vi, en, ja, ko, ...', max_length=10, verbose_name='Ngôn ngữ')),
                ('voice_region', models.CharField(blank=True, default='', help_text='Miền Bắc, Miền Trung, Miền Nam, ...', max_length=50, verbose_name='Giọng vùng miền')),
                ('media_type', models.CharField(choices=[('image', 'Hình ảnh'), ('audio', 'Âm thanh'), ('video', 'Video')], default='image', max_length=10, verbose_name='Loại media')),
                ('status', models.IntegerField(choices=[(0, 'Không hoạt động'), (1, 'Hoạt động')], default=1, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
    ]
