# Generated by Django 5.2.11 on 2026-03-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pois', '0005_partner_status_pending_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='poi_id',
        ),
        migrations.AddField(
            model_name='media',
            name='poi',
            field=models.ForeignKey(blank=True, help_text='Điểm tham quan liên kết', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_media', to='pois.poi', verbose_name='Mã điểm tham quan'),
        ),
    ]
